name: ekasir_api
description: Backend API server for e-Kasir POS application
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  uuid: ^4.2.2
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.12.1
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
